packages:
  - apps/*
  - config/*
  - packages/*
  - scripts

catalog:
  "@tanstack/query-async-storage-persister": 5.62.2
  "@tanstack/react-query": 5.62.2
  "@tanstack/react-query-persist-client": 5.62.2
  "@trpc/client": 11.0.0-rc.648
  "@trpc/next": 11.0.0-rc.648
  "@trpc/react-query": 11.0.0-rc.648
  "@trpc/server": 11.0.0-rc.648
  "superjson": "2.2.1"
  eslint: ^9.12.0
  zod: ^3.23.8
